-- ============================================================
-- V26: Extended deviation seed data
-- Adds more food and alcohol deviations spread over 3 months
-- to provide better data for dashboard graphs.
-- ============================================================

-- ---- FOOD DEVIATIONS (Org 1 - Everest Sushi & Fusion) ----
INSERT INTO food_deviations (organization_id, reported_at, reported_by_user_id, deviation_type, severity,
    description, immediate_action, immediate_action_by_user_id, immediate_action_at,
    cause, preventive_measures, preventive_responsible_user_id, preventive_deadline, status)
VALUES
    -- ~90 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 88 DAY), 4,
     'TEMPERATUR', 'HIGH',
     'Fryser viste -12°C etter nattens strømbrudd. Frossenfisk delvis opptint.',
     'Kastet alt som var opptint. Tekniker tilkalt.',
     4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 88 DAY),
     'Strømbrudd grunnet vedlikeholdsarbeid i bygget.',
     'Installere UPS for frysere. Sjekke temperatur som del av åpningsrutine.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 81 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 85 DAY), 8,
     'RENHOLD', 'LOW',
     'Gulvet bak kjøledisken ikke vasket på tre dager grunnet manglende utstyr.',
     'Bestilt nye moppehoder. Rengjort manuelt med klut.',
     8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 85 DAY),
     'Moppehoder var utslitt og ikke erstattet i tide.',
     'Legge inn bestillingsrutine for rengjøringsutstyr ved månedlig inventar.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 78 DAY),
     'CLOSED'),

    -- ~80 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 80 DAY), 3,
     'MOTTAKSKONTROLL', 'MEDIUM',
     'Leveranse av laks hadde temperatur 8°C ved mottak. Grense er 4°C.',
     'Hele partiet (6 kg) returnert til leverandør. Benyttet reservelager.',
     3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 80 DAY),
     'Transportkjøling hadde sviktet under levering.',
     'Kreve temperaturlogg fra transportør. Umiddelbar temperatursjekk ved mottak.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 73 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 77 DAY), 4,
     'PERSONLIG_HYGIENE', 'LOW',
     'Kokk observert uten hårnet under tilberedning av sashimi.',
     'Påminnet om krav. Hårnet tatt på umiddelbart.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 77 DAY),
     'Glemt i stresset morgenrutine.',
     'Henge påminnelseskilt ved inngang til ren sone.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 70 DAY),
     'CLOSED'),

    -- ~70 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 72 DAY), 4,
     'TEMPERATUR', 'MEDIUM',
     'Kjøleskap 3 svinger mellom 3°C og 6°C. Ustabil termostat.',
     'Ømfintlige varer flyttet til kjøleskap 1. Tekniker bestilt.',
     4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 72 DAY),
     'Termostat har slitasje etter lang bruk.',
     'Planlegge utskifting av termostat innen 2 uker.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 65 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 68 DAY), 8,
     'SKADEDYR', 'HIGH',
     'Funnet muselort i tørrlageret nær rissekker.',
     'Alt ris i åpne sekker kastet. Lager desinfisert. Skadedyrfirma kontaktet.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 68 DAY),
     'Dør til bakgård stod åpen under varemottak kvelden før.',
     'Montere selvlukkende dørpumpe. Plassere musefeller som forebyggende tiltak.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 61 DAY),
     'CLOSED'),

    -- ~60 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 62 DAY), 3,
     'ALLERGEN', 'HIGH',
     'Soyasaus brukt i marinade uten at den var oppført i allergenmerking for retten.',
     'Retten fjernet fra menyen umiddelbart. Allergenliste oppdatert.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 62 DAY),
     'Ny oppskrift fra kokk inneholdt soyasaus, men allergenliste var ikke oppdatert.',
     'Alle oppskriftsendringer skal godkjennes av kjøkkensjef med allergenkontroll.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 55 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 58 DAY), 4,
     'RENHOLD', 'MEDIUM',
     'Kjøkkenventilasjon hadde synlig fettansamling. Branntilsynet kommenterte det under inspeksjon.',
     'Ekstra dyprengjøring av ventilasjon bestilt og utført innen 48 timer.',
     8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 56 DAY),
     'Rengjøringsintervall for ventilasjon var for langt (6 mnd).',
     'Korte ned rengjøringsintervall til kvartalsvis.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 51 DAY),
     'CLOSED'),

    -- ~50 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 52 DAY), 7,
     'TEMPERATUR', 'LOW',
     'Bain-marie var kun 55°C ved lunsjservice. Kravet er 60°C.',
     'Temperatur økt. Mat som stod under 60°C i over 30 min ble kastet.',
     4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 52 DAY),
     'Bain-marie slått på for sent. Trengte lenger tid for oppvarming.',
     'Starte bain-marie minst 45 min før service.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 45 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 48 DAY), 8,
     'PERSONLIG_HYGIENE', 'MEDIUM',
     'Ansatt gikk fra toalett til kjøkken uten å vaske hender. Observert av kjøkkensjef.',
     'Ansatt sendt tilbake for håndvask. Alvorlig samtale gjennomført.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 48 DAY),
     'Stress og høy pågang. Ansatt var ny og vant til annen rutine.',
     'Repetere hygienerutiner ved oppstart for alle nye ansatte.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 41 DAY),
     'CLOSED'),

    -- ~40 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 42 DAY), 4,
     'MOTTAKSKONTROLL', 'LOW',
     'Leveranse av grønnsaker inneholdt salat med synlige skader og begynnende forråtnelse.',
     'Defekte varer returnert. Supplerende ordre plassert hos alternativ leverandør.',
     3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 42 DAY),
     'Leverandør hadde lagret for varmt under transport.',
     'Dokumentere varekvalitet med foto ved mottak. Reklamere skriftlig.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 35 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 38 DAY), 3,
     'ANNET', 'LOW',
     'Datomerking på 8 porsjoner maki ikke lesbar grunnet fuktig emballasje.',
     'Porsjoner merket på nytt. Ingen kassering nødvendig.',
     3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 38 DAY),
     'Vannsprut fra oppvask traff emballeringsstasjon.',
     'Flytte emballeringsstasjonen lenger fra oppvaskområdet.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 31 DAY),
     'CLOSED'),

    -- ~30 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 32 DAY), 4,
     'TEMPERATUR', 'MEDIUM',
     'Kjøleskap 2 målte 5.8°C etter at dør ble stående åpen under varemottak.',
     'Dør lukket. Temperatur sjekket etter 30 min — tilbake til 3°C.',
     4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 32 DAY),
     'Stor vareleveranse krevde at dør stod åpen lenger enn vanlig.',
     'Bruke kjølebag for mellomlagring under store leveranser.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY), 8,
     'RENHOLD', 'LOW',
     'Skjærefjøler i plast hadde dype riper og var vanskelige å rengjøre tilstrekkelig.',
     'Fjølene byttet ut umiddelbart med nye.',
     8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY),
     'Fjølene var ikke byttet på over ett år.',
     'Kvartalsvis inspeksjon av alt skjæreutstyr.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY),
     'CLOSED'),

    -- ~20 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY), 4,
     'ALLERGEN', 'CRITICAL',
     'Gjest med melkeallergi fikk servering av rett med skjult meierismør. Allergisk reaksjon oppstod.',
     'Akutt: Antihistamin tilbudt. Ambulanse tilkalt som forholdsregel. Gjest stabilisert.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY),
     'Kokk brukte smør i stedet for olje ved starten av servicen uten å oppdatere kjøkkenseddel.',
     'Absolutt nulltoleranse: Alle ingrediensbytter skal godkjennes skriftlig. Dobbeltsjekk ved allergiflagg.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY),
     'UNDER_TREATMENT'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY), 3,
     'TEMPERATUR', 'LOW',
     'Temperaturlogg for fredag ble ikke ført. Oppdaget mandag morgen.',
     'Logg etterskrevet basert på generell observasjon. Avvik notert.',
     3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY),
     'Fredagsvakten glemte å føre logg i slutten av skiftet.',
     'Sette opp push-varsel kl. 22:00 hvis logg ikke er ført.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 11 DAY),
     'CLOSED'),

    -- ~14 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY), 7,
     'RENHOLD', 'MEDIUM',
     'Ismaskin ikke rengjort på 5 dager. Synlig belegg i dispenserdelen.',
     'Maskin demontert og grundig rengjort. Bakterieprøve tatt.',
     8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY),
     'Ingen klar ansvarsfordeling for rengjøring av ismaskin.',
     'Legge ismaskin-rengjøring inn i daglig sjekkliste.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY),
     'CLOSED'),

    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 13 DAY), 4,
     'MOTTAKSKONTROLL', 'MEDIUM',
     'Vakuumpakket tunfisk hadde oppblåst emballasje — tegn på bakterievekst.',
     'Hele partiet (4 pakker) kassert. Leverandør varslet.',
     4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 13 DAY),
     'Brudd i kjølekjede under transport.',
     'Innføre visuell inspeksjon av vakuumemballasje som standard mottakskontroll.',
     2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY),
     'CLOSED'),

    -- ~7 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY), 3,
     'PERSONLIG_HYGIENE', 'LOW',
     'Servitør observert med løst hår over matserveringsdisk.',
     'Bedt om å sette opp håret. Hårstrikk utdelt.',
     3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY),
     'Ansatt var ikke klar over kravet for serveringspersonale.',
     'Inkludere hygienekrav for servitører i opplæringsmaterial.',
     2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY),
     'OPEN'),

    -- ~3 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY), 4,
     'TEMPERATUR', 'HIGH',
     'Mottakskontroll av sjømat viste 7.2°C. Grenseverdi for fersk sjømat er 2°C.',
     'Leveranse avvist i sin helhet (15 kg). Alternativ leverandør kontaktet.',
     4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY),
     'Leverandørs kjølebil hadde feil på aggregat.',
     'Kreve dokumentert temperaturlogg fra leverandør. Vurdere bytte av leverandør.',
     2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 10 DAY),
     'OPEN'),

    -- ~1 day ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 8,
     'RENHOLD', 'LOW',
     'Kjøkkengulv glatt etter manglende tørking etter vask. Potensiell skaderisiko.',
     'Gulv tørket umiddelbart. Skilt om vått gulv satt opp.',
     8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY),
     'Renholder var alene og hadde ikke tid til å tørke.',
     'Sørge for at det alltid er tilgjengelig «vått gulv»-skilt og tørkeutstyr.',
     2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY),
     'OPEN'),

    -- Nordvik food deviations (spread over time)
    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 75 DAY), 6,
     'TEMPERATUR', 'MEDIUM',
     'Kjøleskap bak baren viste 6.5°C. Øl og melkeprodukter lagret der.',
     'Varer flyttet. Termostat justert.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 75 DAY),
     'Kjøleskap overbelastet under helgens varemottak.',
     'Ikke overfylle kjøleskap. Fordele varer bedre.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 68 DAY),
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 55 DAY), 5,
     'RENHOLD', 'LOW',
     'Glassvaskmaskin ikke tømt for restevann etter stenging. Lukt oppdaget neste dag.',
     'Maskin tømt og rengjort. Desinfisert.',
     5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 55 DAY),
     'Helgevakt glemte lukkerutine.',
     'Legge tømming av glassvasker i lukkesjekkliste.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 48 DAY),
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 35 DAY), 7,
     'PERSONLIG_HYGIENE', 'LOW',
     'Bartender brukte mobiltelefon ved bardisken mellom drinktilberedning.',
     'Påminnet om hygieneregler. Mobil lagt i skuff.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 35 DAY),
     'Ingen klar policy om mobilbruk bak bar.',
     'Innføre mobilfri sone bak bar og kjøkken under arbeidstid.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY),
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY), 6,
     'MOTTAKSKONTROLL', 'MEDIUM',
     'Leveranse av kylling hadde brutt kjølekjede. Temperatur 9°C.',
     'Leveranse returnert. Erstatningsleveranse bestilt.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY),
     'Transportør hadde for mange stopp på ruten.',
     'Krav om maks 2 timer transport i kontrakt med leverandør.',
     6, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY),
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY), 5,
     'TEMPERATUR', 'LOW',
     'Barens mini-kjøleskap for garnish viste 7°C. Lime og sitron lagret der.',
     'Garnish flyttet til hovedkjøleskap. Termostat på mini-kjøleskap justert.',
     5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY),
     'Mini-kjøleskapet er gammelt og holder ikke stabil temperatur.',
     'Vurdere utskifting av mini-kjøleskapet.',
     6, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 14 DAY),
     'OPEN');

-- ---- ALCOHOL DEVIATIONS (Org 1 - Everest Sushi & Fusion) ----
INSERT INTO alcohol_deviations (organization_id, reported_at, reported_by_user_id, report_source,
    deviation_type, description, immediate_action, causal_analysis, causal_explanation,
    preventive_measures, preventive_deadline, preventive_responsible_user_id, status)
VALUES
    -- ~85 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 85 DAY), 5,
     'EGENRAPPORT', 'BRUDD_SJENKETIDER',
     'Sake ble servert 5 minutter etter skjenketid (kl. 02:05). Oppdaget ved kasseoppgjør.',
     'Siste bestillinger stoppes kl. 01:45 heretter.',
     'RUTINE_IKKE_FULGT',
     'Bartender hadde ikke klokke synlig og gikk etter feeling.',
     'Montere klokke synlig bak bar. Alarm kl. 01:30 og 01:45.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 78 DAY), 2,
     'CLOSED'),

    -- ~75 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 75 DAY), 7,
     'EGENRAPPORT', 'GLEMTE_SJEKKE_LEGITIMASJON',
     'Ung gjest (viste seg å være 19) ble servert vin uten ID-sjekk. Oppdaget av kollega.',
     'ID kontrollert i etterkant — gjesten var over 18.',
     'MANGLENDE_OPPLAERING',
     'Ny servitør var usikker på alderskrav og turte ikke spørre.',
     'Alle nye ansatte gjennomgår ID-sjekk-trening med rollespill første uke.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 68 DAY), 2,
     'CLOSED'),

    -- ~60 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 60 DAY), 5,
     'EGENRAPPORT', 'SKJENKING_APENBART_BERUSET',
     'Gjest i baren viste tegn på sterk beruselse (snøvlet, sølt). Ble likevel servert én øl til av vikar.',
     'Servering stoppet. Gjest tilbudt taxi og vann.',
     'MANGLENDE_OPPLAERING',
     'Vikarbartender hadde ikke fått opplæring i beruselsestegn.',
     'Vikarer må gjennomgå mini-kurs i ansvarlig servering før første vakt.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 53 DAY), 2,
     'CLOSED'),

    -- ~45 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 45 DAY), 2,
     'SJENKEKONTROLL', 'ALKOHOLFRI_ALTERNATIV_MANGLER',
     'Kommunal kontroll påpekte at det ikke fantes alkoholfrie alternativer synlig i meny eller bardisk.',
     'Alkoholfri øl og mocktails lagt til menyen umiddelbart.',
     'RUTINE_MANGLER',
     'Menyen var ikke oppdatert etter forrige sesongbytte.',
     'Sikre at alkoholfrie alternativer alltid er synlig i meny og på bardisk.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 38 DAY), 2,
     'CLOSED'),

    -- ~30 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 30 DAY), 5,
     'EGENRAPPORT', 'MINDREAARIG_FORSOK',
     '16-åring forsøkte å bestille cocktail. Ble avslørt ved ID-sjekk.',
     'Servering nektet. Gjest informert om aldersgrense.',
     'ANNET',
     'Gjest hadde lånt eldre søskens ID.',
     'Opplæring i å gjenkjenne falske/lånte ID-er.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY), 2,
     'CLOSED'),

    -- ~20 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY), 7,
     'EGENRAPPORT', 'NEKTET_VISE_LEGITIMASJON',
     'Gjest ble aggressiv da servitør ba om legitimasjon. Truet med dårlig anmeldelse.',
     'Servering nektet. Vakt informert. Gjest roet seg og forlot.',
     'ANNET',
     'Gjest var tydelig voksen men opplevde kravet som fornærmende.',
     'Opprettholde konsekvent policy. Trene personalet i konflikthåndtering.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 13 DAY), 2,
     'CLOSED'),

    -- ~14 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY), 5,
     'EGENRAPPORT', 'BRUDD_SJENKETIDER',
     'Cocktail servert kl. 02:10 under privat arrangement. Arrangementet hadde ikke utvidet bevilling.',
     'Bar stengt umiddelbart. Kun alkoholfritt servert videre.',
     'KOMMUNIKASJON',
     'Bartender trodde privat arrangement hadde utvidet skjenketid.',
     'Skriftlig bekreftelse av skjenketider for alle arrangementer. Info synlig ved bar.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 7 DAY), 2,
     'UNDER_TREATMENT'),

    -- ~7 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 7 DAY), 3,
     'EGENRAPPORT', 'FALSK_LEGITIMASJON',
     'Servitør mistenkte falskt pass fra gjest. Sammenlignet bilde — tydelig mismatch.',
     'Servering nektet. Legitimasjon fotografert og hendelse loggført.',
     'ANNET',
     'Gjest brukte annen persons pass.',
     'Opplæring i å gjenkjenne sikkerhetselementer i pass og førerkort.',
     DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY), 2,
     'OPEN'),

    -- ~4 days ago
    (1, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY), 5,
     'EGENRAPPORT', 'BERUSET_PERSON_I_LOKALET',
     'To gjester i restaurantdelen var tydelig beruset etter pre-party. Var høylytte og forstyrrende.',
     'Gjestene ble bedt om å dempe seg. Videre servering av alkohol nektet. Tilbudt kaffe.',
     'RUTINE_IKKE_FULGT',
     'Gjestene ble sluppet inn av dørvakt uten observasjon av beruselsesgrad.',
     'Dørvakt skal gjøre en vurdering av beruselsesgrad ved innslipp på kveldsarrangementer.',
     DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 10 DAY), 2,
     'OPEN'),

    -- Nordvik alcohol deviations (spread over time)
    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 70 DAY), 7,
     'EGENRAPPORT', 'GLEMTE_SJEKKE_LEGITIMASJON',
     'Ung gjest bestilte øl og ble servert uten ID-sjekk. Kollega påpekte det etterpå.',
     'ID sjekket i etterkant — gjest var 20 år.',
     'HOYT_TRYKK_STRESS',
     'Stor pågang ved bardisken. Servitør prioriterte hastighet.',
     'Alltid spørre om ID uansett pågang. Ekstra personale i bar ved helg.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 63 DAY), 6,
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 50 DAY), 5,
     'SJENKEKONTROLL', 'BRUDD_SJENKETIDER',
     'Kommunal kontroll kl. 02:15 avdekket at det fortsatt ble servert øl.',
     'Bar stengt umiddelbart. Beklaget overfor kontrollør.',
     'RUTINE_IKKE_FULGT',
     'Bartender hadde ikke fått beskjed om skjenketid.',
     'Skjenketider henges opp synlig bak bar. Alarm i kassesystemet.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 43 DAY), 6,
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY), 6,
     'EGENRAPPORT', 'SKJENKING_APENBART_BERUSET',
     'Gjest som allerede var synlig beruset ble servert shot av vikarbartender.',
     'Videre servering stoppet. Gjest tilbudt taxi.',
     'MANGLENDE_OPPLAERING',
     'Vikarbartender hadde ikke fått opplæring.',
     'Obligatorisk intro-kurs for alle vikarer før de serverer alkohol.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY), 6,
     'CLOSED'),

    (2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY), 7,
     'EGENRAPPORT', 'MINDREAARIG_FORSOK',
     '17-åring forsøkte å kjøpe drink med falskt førerkort. Avslørt ved nøye sjekk.',
     'Servering nektet. Foreldre kontaktet.',
     'ANNET',
     'Gjest hadde tilsynelatende ekte førerkort, men hologram manglet.',
     'Gjennomgang av hologram og sikkerhetselementer i opplæring.',
     DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 6,
     'CLOSED');
