-- ============================================================
-- V27: Extended checklist completion history
-- Adds realistic completion records over the last 30 days
-- for daily checklists to populate the dashboard chart.
-- ============================================================

INSERT INTO checklist_completions (checklist_id, organization_id, completed_by_user_id, completed_at) VALUES
    -- Everest (org 1): Checklist 1 - Åpningsrutiner kjøkken (DAILY)
    -- Completed almost every day for the past 30 days
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 30 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 29 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 27 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
    -- missed day 21
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 13 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 12 DAY)),
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 11 DAY)),
    (1, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
    -- missed day 9
    (1, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),

    -- Everest: Checklist 2 - Stengerutiner kjøkken (DAILY)
    -- Completed most days but with more gaps
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 30 DAY)),
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 29 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY)),
    -- missed 27
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY)),
    -- missed 22
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY)),
    -- missed 17
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 13 DAY)),
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 12 DAY)),
    -- missed 11
    (2, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
    (2, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),

    -- Everest: Checklist 3 - Personlig hygiene (DAILY)
    -- Rarely completed - low compliance
    (3, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 29 DAY)),
    (3, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
    (3, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
    (3, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
    (3, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 12 DAY)),
    (3, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),

    -- Everest: Checklist 4 - Skjenkekontroll kveldsvakt (DAILY)
    -- Good compliance, some gaps on weekends
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 30 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 29 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 27 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 12 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 11 DAY)),
    (4, 1, 4, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
    (4, 1, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),

    -- Nordvik (org 2): Checklist 11 - Åpningsrutiner bar (DAILY)
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 30 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 29 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 27 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
    -- missed 24
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
    -- missed 18
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 13 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 12 DAY)),
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 11 DAY)),
    (11, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
    -- missed 9
    (11, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),

    -- Nordvik: Checklist 12 - Stengerutiner bar og kjøkken (DAILY)
    (12, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 29 DAY)),
    (12, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 28 DAY)),
    (12, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY)),
    (12, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
    (12, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
    (12, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
    (12, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY)),
    (12, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
    (12, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
    (12, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 12 DAY)),
    (12, 2, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
    (12, 2, 7, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY));
